# Generated by Django 5.2.6 on 2025-09-09 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
        ("users", "0002_remove_user_is_active_userprofile_gender_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="accessible_branches",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="company",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="is_company_admin",
        ),
        migrations.AddField(
            model_name="user",
            name="accessible_branches",
            field=models.ManyToManyField(
                blank=True, related_name="users_with_access", to="companies.branch"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="companies.company",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_company_admin",
            field=models.BooleanField(default=False),
        ),
    ]
