# Generated by Django 5.2.6 on 2025-09-23 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("c_auth", "0001_initial"),
        ("users", "0004_user_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="c_groups",
            field=models.ManyToManyField(blank=True, to="c_auth.cgroup"),
        ),
    ]
