# Generated by Django 5.2.6 on 2025-09-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_c_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="admin_access",
            field=models.BooleanField(default=False),
        ),
    ]
