# Generated by Django 5.2.6 on 2025-09-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stockbatch",
            old_name="purchase_price",
            new_name="discount",
        ),
        migrations.AlterField(
            model_name="stockbatch",
            name="quantity",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
