# Generated by Django 5.2.6 on 2025-09-11 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0002_rename_purchase_price_stockbatch_discount_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockbatch",
            name="discount",
        ),
    ]
