# Generated by Django 5.2.6 on 2025-09-11 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_branchproduct_stock"),
        ("stock", "0003_remove_stockbatch_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockbatch",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="batches",
                to="products.branchproduct",
            ),
        ),
    ]
