# Generated by Django 5.2.6 on 2025-09-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0004_alter_stockbatch_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockbatch",
            name="selling_price",
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="stockbatch",
            name="unit_cost",
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
    ]
