# Generated by Django 5.2.6 on 2025-09-11 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0005_stockbatch_selling_price_stockbatch_unit_cost"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stockbatch",
            old_name="unit_cost",
            new_name="cost",
        ),
    ]
