# Generated by Django 5.2.6 on 2025-09-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0006_rename_unit_cost_stockbatch_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockbatch",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
