# Generated by Django 5.2.6 on 2025-09-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name_plural": "Products"},
        ),
        migrations.AlterUniqueTogether(
            name="product",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="product",
            name="product_code",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name="product",
            name="sku",
        ),
    ]
