# Generated by Django 5.2.6 on 2025-09-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0002_alter_product_options_alter_product_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="unit_price",
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
