# Generated by Django 5.2.6 on 2025-09-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_product_unit_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="branchproduct",
            name="stock",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
