# Generated by Django 5.2.6 on 2025-09-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="branch",
            name="phone_1",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Phone 1"
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="phone_2",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Phone 2"
            ),
        ),
    ]
