# Generated by Django 5.2.6 on 2025-09-22 18:28

import accounts.c_auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, unique=True, verbose_name="name"),
                ),
                ("description", models.TextField()),
            ],
            options={
                "verbose_name": "group",
                "verbose_name_plural": "groups",
            },
            managers=[
                ("objects", accounts.c_auth.models.CGroupManager()),
            ],
        ),
        migrations.CreateModel(
            name="CGroupPermissions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cgroup_permissions",
                        to="c_auth.cgroup",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.permission",
                    ),
                ),
            ],
            options={
                "unique_together": {("group", "permission")},
            },
        ),
        migrations.AddField(
            model_name="cgroup",
            name="permissions",
            field=models.ManyToManyField(
                blank=True,
                through="c_auth.CGroupPermissions",
                to="auth.permission",
                verbose_name="permissions",
            ),
        ),
    ]
