# Generated by Django 5.2.6 on 2025-09-11 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_branchproduct_stock"),
        ("sales", "0002_saleitem_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="saleitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sales",
                to="products.branchproduct",
            ),
        ),
    ]
