# Generated by Django 5.2.6 on 2025-09-11 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0003_alter_saleitem_product"),
        ("stock", "0005_stockbatch_selling_price_stockbatch_unit_cost"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sale",
            name="total_amount",
        ),
        migrations.AddField(
            model_name="saleitem",
            name="stock_batch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sales",
                to="stock.stockbatch",
            ),
        ),
    ]
