# Generated by Django 5.2.6 on 2025-09-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0004_remove_sale_total_amount_saleitem_stock_batch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="saleitem",
            name="discount",
            field=models.DecimalField(
                blank=True, decimal_places=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="saleitem",
            name="quantity",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="saleitem",
            name="unit_price",
            field=models.DecimalField(
                blank=True, decimal_places=0, max_digits=10, null=True
            ),
        ),
    ]
