# Generated by Django 5.2.6 on 2025-09-12 11:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0005_alter_saleitem_discount_alter_saleitem_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
