# Generated by Django 5.2.6 on 2025-09-23 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0006_alter_sale_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sale",
            options={
                "ordering": ["-date"],
                "permissions": [("analyze_profit", "Can analyze profit")],
                "verbose_name": "Sale",
                "verbose_name_plural": "Sales",
            },
        ),
    ]
